### ISSUE TITLE
Annotated images link to directly to image page, not item page

### ISSUE THREAD

**Issue by emeehangsu** [omeka/plugin-ExhibitImageAnnotation#10]
I'm trying to build an exhibit that makes use of annotated images, however I can't figure out how to have the annotated images link to the item that the image was derived from.

Is this possible?

Essentially its linking to:
 /omeka/files/show/2
while I would like it to link to:
omeka/items/show/5

**Comment by jimsafley** [comment]
The annotated image should have always linked to the exhibit item page. Fixed in the next release, which should be available shortly.
