### ISSUE TITLE
Test the Exhibit Image Annotation plugin

### ISSUE THREAD

**Issue by jimsafley** [omeka/plugin-ExhibitImageAnnotation#4]
This plugin adds an "Image Annotation" layout to exhibit pages. It's much like the "File" layout except the user can annotate the image using a simple interface.

After installing the plugin confirm that you can add the layout to a page, that you can add only one item to the block, that the image you selected loads after pressing the "Load selected image" button, and that you can annotate the image. Save the page and confirm that the annotations you added are still there.

**Comment by mebrett** [comment]
Annotations are only visible on the admin side (expected behavior), and annotations are saved when the page is saved.

I was also able to annotate pdf, txt, and mp4 files - the "load selected image" option gave me either the first page (txt,pdf) or the first frame (video).
